// The numbers the animation shows, all regenerated by math/rope.js from attention's head A (storyboard §5, "Numbers shown").
// Frozen at import; nothing here touches the DOM.
import { deepFreeze } from '@math/core.js';
import { ropeFrequencies, rotatePairs, ropeScore, scoreByOffset, stretchFrequencies, angleCoverage, wavelengths } from '@math/rope.js';
import { Q_SAT, keyVector, OFFSETS, TRAINED_LENGTH } from './format.js';

export const K_CAT = keyVector(1);
export const POS = deepFreeze({ q: 3, k: 2, shift: 10, readTo: 64 }); // "sat" is token 3, "cat" token 2 (1-based, as on screen)
export const STRETCH_FACTOR = POS.readTo / TRAINED_LENGTH; // 4: trained on 16 tokens, read to 64

export const FREQS = deepFreeze(ropeFrequencies(4, 100)); // [1, 0.1]
export const FREQS_10K = deepFreeze(ropeFrequencies(4, 10_000)); // [1, 0.01]
export const PI_FREQS = deepFreeze(stretchFrequencies(FREQS, { factor: STRETCH_FACTOR, method: 'pi', trainedLength: TRAINED_LENGTH }));
export const YARN_FREQS = deepFreeze(stretchFrequencies(FREQS, { factor: STRETCH_FACTOR, method: 'yarn-simple', trainedLength: TRAINED_LENGTH }));
export const WAVELENGTHS = deepFreeze(wavelengths(FREQS));

// The query and key as two pairs each: the lengths 2, 0.5, 1.5, 0.5 are what the dials print.
const pairs = (vec) => [[vec[0], vec[1]], [vec[2], vec[3]]];
export const Q_PAIRS = deepFreeze(pairs(Q_SAT));
export const K_PAIRS = deepFreeze(pairs(K_CAT));

export const SCORE = deepFreeze(ropeScore(Q_SAT, K_CAT, { qPos: POS.q, kPos: POS.k, freqs: FREQS }));
export const PLAIN_SCORE = Q_SAT.reduce((sum, x, i) => sum + x * K_CAT[i], 0); // 3.0, the unrotated q . k
export const Q_AT = (pos) => rotatePairs(Q_SAT, pos, FREQS);
export const K_AT = (pos) => rotatePairs(K_CAT, pos, FREQS);

const rowFor = (freqs) => deepFreeze(scoreByOffset(Q_SAT, K_CAT, { freqs, offsets: OFFSETS }));
export const ROW = deepFreeze({ base100: rowFor(FREQS), base10000: rowFor(FREQS_10K), pi: rowFor(PI_FREQS), yarn: rowFor(YARN_FREQS) });

// Frame 8: angles seen in training (offsets 0-15) against the angles reached at 64 tokens, with and without the squeeze.
export const COVERAGE = deepFreeze({
  plain: angleCoverage(FREQS, { trainedLength: TRAINED_LENGTH, length: POS.readTo }),
  pi: angleCoverage(PI_FREQS, { trainedLength: TRAINED_LENGTH, length: POS.readTo, trainedFreqs: FREQS }),
});
// The largest offset the model has seen, and the one it is asked to read.
export const TRAINED_MAX_OFFSET = TRAINED_LENGTH - 1;
export const READ_MAX_OFFSET = POS.readTo - 1;
