// The sampling stage's shared kit: layout constants, the numbers every frame shows (all from math/sampling.js),
// timing helpers and the few drawing helpers the frames share. Nothing touches the DOM at import time.
import * as G from '@shared/glyphs.js';
import { LOGITS, NAMED, applyTemperature, collapseOthers, topK, topP } from '@math/sampling.js';
import { probText, scoreText, trimNumber } from './format.js';

export const STAGE = Object.freeze({ w: 580, h: 366 });
export const CELL = G.NUMBER_CELL; // numbers the learner reads
export const SCORE_MAX = 2; // README: scores on maxAbs 2, probabilities on maxAbs 1
export const PROB_MAX = 1;

// ---- layout: fixed positions shared by the frames ----
export const ROW_X = 84; // leaves room for a row label such as "scores ÷ T" to its left
export const ROW_W = 5 * CELL;
export const RIGHT_X = ROW_X + ROW_W + 16; // notes to the right of a five-cell row
export const CHIP_Y = 6;
export const CHIP_GAP = 8;
export const SLOT_W = 36; // a slot keeps its width whatever token sits in it, so nothing shifts
const CONTEXT = Object.freeze(['The', 'cat', 'sat', 'down']);
const contextX = (i) => ROW_X + CONTEXT.slice(0, i).reduce((sum, w) => sum + G.tokenWidth(w) + CHIP_GAP, 0);
export const SLOT_X = Object.freeze({ five: contextX(CONTEXT.length), six: contextX(CONTEXT.length) + SLOT_W + CHIP_GAP });
export const FIVE_Y = Object.freeze({ scores: 98, probs: 198 }); // frames 1–2
export const SHAPE_Y = Object.freeze({ scores: 74, before: 150, after: 226 }); // frames 4–6
export const NOTE_PAD = 14; // a note under a row sits this far below its bottom edge

// ---- timing ----
export const clamp01 = (t) => Math.min(Math.max(t, 0), 1);
export const seg = (p, a, b) => clamp01((p - a) / (b - a)); // progress p remapped to the sub-phase [a, b]
export const lerp = (a, b, t) => a + (b - a) * t;
export const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - (-2 * t + 2) ** 2 / 2);
// Each frame starts from the previous frame's end state: what leaves fades out and what arrives fades in during [0, HANDOFF].
export const HANDOFF = 0.15;
export const arriving = (p) => seg(p, 0, HANDOFF);
export const leaving = (p) => 1 - seg(p, 0, HANDOFF);

// ---- the numbers (storyboard §5 "Numbers shown"; regenerated by math/sampling.js) ----
export const WORDS = Object.freeze(['on', '"."', 'and', 'the', '12 others']);
export const SCORE_CELLS = Object.freeze([...NAMED.map((i) => LOGITS[i]), LOGITS[LOGITS.findIndex((_, i) => !NAMED.includes(i))]]);
export const OTHERS = LOGITS.length - NAMED.length;

// Five cells for a probability vector: the four named words, then the value of each of the 12 others.
export const fiveCells = (probs) => {
  const { named, others } = collapseOthers(probs, NAMED);
  return Object.freeze([...named, others.each]);
};
export const probsAt = (temperature) => applyTemperature(LOGITS, temperature);
export const cellsAt = (temperature) => fiveCells(probsAt(temperature));
export const togetherAt = (temperature) => collapseOthers(probsAt(temperature), NAMED).others.together;
export const RESULT = Object.freeze({ k3: topK(probsAt(1), 3), p7: topP(probsAt(1), 0.7) }); // frames 5 and 6 (same three tokens)

// ---- drawing helpers ----
// A group at the given opacity (attribute omitted when fully opaque, so frames at rest stay plain).
export const layer = (svg, opacity = 1) => G.svgEl('g', { opacity: opacity < 1 ? opacity.toFixed(3) : null }, svg);

// A plain labeled text mark (README lesson 15), styled like glyph labels. `link` makes it a math-panel target:
// an invisible frame around the text (about 6.7 px a character) is what the hover outlines.
const CHAR_W = 6.7;
export function note(parent, x, y, str, { anchor = 'start', opacity = 1, link = null } = {}) {
  const outer = link ? G.svgEl('g', { 'data-link': link }, parent) : parent;
  if (link) {
    const w = str.length * CHAR_W + 6;
    const left = anchor === 'middle' ? x - w / 2 : x - 3;
    G.svgEl('rect', { class: 'g-frame', x: left, y: y - 9, width: w, height: 18, rx: 3, fill: 'none', stroke: 'none' }, outer);
  }
  const g = G.svgEl('g', { class: 'glyph g-note', opacity: opacity < 1 ? opacity.toFixed(3) : null }, outer);
  const t = G.svgEl('text', { x, y, class: 'g-label', 'text-anchor': anchor, 'dominant-baseline': 'central' }, g);
  t.textContent = str;
  return g;
}

// A thin vertical rule (a boundary tick). It reuses the glyph frame stroke, so it follows the theme.
export function tick(parent, x, y1, y2) {
  const g = G.svgEl('g', { class: 'glyph g-note' }, parent);
  G.svgEl('line', { class: 'g-frame', x1: x, y1, x2: x, y2 }, g);
  return g;
}

// ---- chips: "The cat sat down" and the slots being filled ----
export const CHIP_H = 24;

// One token in a slot (position 5 or 6): `state` 'draft' is the library's dashed state, never hatched.
export function slotChip(svg, slot, text, { state = 'idle', opacity = 1, at = null } = {}) {
  const x = at?.x ?? SLOT_X[slot];
  const y = at?.y ?? CHIP_Y;
  const g = G.token(layer(svg, opacity), { x, y, text, index: slot === 'five' ? 5 : 6, state });
  return { g, x, y, w: G.tokenWidth(text) };
}

export function selectChip(svg, { x, y, text, opacity = 1 }) {
  if (opacity <= 0) return;
  G.selectionMark(layer(svg, opacity), { x, y, w: G.tokenWidth(text), h: CHIP_H });
}

// The four context chips. `slots` lists what fills positions 5 and 6: [{ slot, text, state, opacity, mark }].
// The followed position carries the selection mark wherever it appears (here: the slot, in every frame).
export function chips(svg, slots = []) {
  CONTEXT.forEach((text, i) => G.token(svg, { x: contextX(i), y: CHIP_Y, text, index: i + 1 }));
  slots.forEach(({ slot, text, state, opacity = 1, mark = 1 }) => {
    const chip = slotChip(svg, slot, text, { state, opacity });
    selectChip(svg, { ...chip, text, opacity: Math.min(opacity, mark) });
  });
}

// ---- five-cell rows ----
export const formatFor = (kind) => (v) => {
  if (v == null || Number.isNaN(v)) return '';
  return kind === 'score' ? scoreText(v) : probText(v);
};

// Word labels above a row: the four names centered on their cells, "12 others" starting at its cell.
export function wordLabels(svg, y, opacity = 1) {
  WORDS.forEach((w, i) => {
    if (i < 4) note(svg, ROW_X + i * CELL + CELL / 2, y, w, { anchor: 'middle', opacity });
    else note(svg, ROW_X + i * CELL + 2, y, w, { opacity });
  });
}

// A five-cell row as a 1 × 5 matrix. `values` may hold null (not computed yet: a blank cell); `hatch[i]` true = cut (excluded).
export function fiveRow(svg, { y, values, kind, name, link, hatch = null, opacity = 1 }) {
  const shown = values.map((v) => (v == null ? Number.NaN : v));
  const g = G.matrix(layer(svg, opacity), {
    x: ROW_X, y, values: [shown], cell: CELL, maxAbs: kind === 'score' ? SCORE_MAX : PROB_MAX, rowLabels: [name], format: formatFor(kind), hatch: hatch ? [hatch] : undefined,
  });
  if (link) g.dataset.link = link;
  return g;
}

export const rowMark = (svg, y, opacity = 1) => G.selectionMark(layer(svg, opacity), { x: ROW_X, y, w: ROW_W, h: CELL });
export const cellMark = (svg, y, i, opacity = 1) => {
  if (opacity > 0) G.selectionMark(layer(svg, opacity), { x: ROW_X + i * CELL, y, w: CELL, h: CELL });
};

// "0.019 each (0.233 together)" under a probability row; a filter that cuts some of the 12 adds "n of 12 kept".
export function othersNote(probs) {
  const { others } = collapseOthers(probs, NAMED);
  if (others.kept === 0) return `all ${others.of} others cut`;
  const base = `${probText(others.each)} each (${probText(others.together)} together)`;
  return others.kept === others.of ? base : `${base} · ${others.kept} of ${others.of} kept`;
}

export const temperatureText = (t) => `T = ${trimNumber(t, 2)}`;
