// The attention stage's shared kit: layout, the numbers every frame shows (all from math/attention.js),
// timing helpers and the few drawing helpers the frames share. Pure: nothing touches the DOM at import time.
import * as G from '@shared/glyphs.js';
import { TOY, attentionHead } from '@math/attention.js';
import { formatFor } from './format.js';

export const STAGE = Object.freeze({ w: 580, h: 366 });
export const CELL = G.NUMBER_CELL; // numbers the learner reads
export const GRID = 20; // Q, K, V: values on hover only (every one is also printed elsewhere)
export const QUERY = 2; // "sat", the row we follow in every frame
export const TOKENS = TOY.tokens;

// ---- the numbers (storyboard §5 "Numbers shown"; regenerated by math/attention.js) ----
const run = ({ Q, K, V }) => attentionHead(Q, K, V);
export const HEAD_A = run(TOY.heads.A);
export const HEAD_B = run(TOY.heads.B);
export const QKV = TOY.heads.A;
export const SCALE = Object.freeze({ qkv: 3, score: 4.5, weight: 1, out: 1.5 }); // storyboard §4 "Color"

// ---- layout, frames 1–8 (fixed positions; the heatmap keeps its place from frame 3 to frame 8) ----
export const TOKEN_Y = 8;
export const TOKEN_X = Object.freeze([50, 98, 146, 194]);
export const W_BLOCK = Object.freeze({ x: 50, y: 40, w: 272, h: 24 });
export const MAT_Y = 92;
export const MAT_X = Object.freeze({ q: 50, k: 146, v: 242 });
export const SHAPE_Y = 188;
export const STRIP_X = 110;
export const STRIP_Y = Object.freeze([204, 247, 290]); // row strip: up to three stacked NUMBER_CELL rows
export const SIDE_X = 280; // "sum 6.372", "Σ = 1.000"
export const NOTE_Y = 352;
export const HEAT = Object.freeze({ x: 390, y: 92 });
export const SCORE_ROW = Object.freeze({ x: 320, y: 225 }); // frame 2's score row, beside the strip
export const CHIP_X = 326; // frame 7's weight chips, beside V
export const OUT_ROW = Object.freeze({ x: 390, y: 290 });
export const O_GRID = Object.freeze({ x: 180, y: 92 });
// frames 9–10: two head blocks side by side, the joined row and W_O below
export const HEADS_Y = 50;
export const HEAD_X = Object.freeze({ A: 56, B: 300 });
export const O_ROW_Y = 214;
export const CONCAT = Object.freeze({ x: 100, y: 284 });
export const W_O = Object.freeze({ x: 460, y: 284, w: 100, h: 40 });

// ---- timing ----
export const clamp01 = (t) => Math.min(Math.max(t, 0), 1);
export const seg = (p, from, to) => clamp01((p - from) / (to - from)); // progress p remapped to the sub-phase [from, to]
export const lerp = (a, b, t) => a + (b - a) * t;
export const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - (-2 * t + 2) ** 2 / 2);

// ---- drawing helpers ----
export function fade(node, opacity) {
  if (opacity < 1) node.style.opacity = String(Math.max(opacity, 0));
  return node;
}

// Plain text marks live in a .glyph group so the stage's one label face and size apply (spec §5.4).
export function label(svg, x, y, str, { anchor = 'start', cls = 'g-label', opacity = 1 } = {}) {
  const g = G.svgEl('g', { class: 'glyph g-note' }, svg);
  const t = G.svgEl('text', { x, y, class: cls, 'text-anchor': anchor, 'dominant-baseline': 'central' }, g);
  t.textContent = str;
  return fade(g, opacity);
}

export const select = (svg, x, y, w, h, opacity = 1) => fade(G.selectionMark(svg, { x, y, w, h }), opacity);

// Glyph values: a cell not computed yet is null (blank, neutral fill); −∞ is a masked cell.
const glyphValues = (values) => values.map((v) => (v == null ? Number.NaN : v));

// A math-linked group: an invisible rect.g-frame the math-panel hover outlines, then the glyph inside it.
function linked(svg, letter, box) {
  if (!letter) return svg;
  const g = G.svgEl('g', { 'data-link': letter }, svg);
  G.svgEl('rect', { class: 'g-frame', x: box.x - 1, y: box.y - 1, width: box.w + 2, height: box.h + 2, rx: 3, fill: 'none', stroke: 'none' }, g);
  return g;
}

// One row of NUMBER_CELL numbers; each cell prints its quantity's format (format.js cellText).
export function numberRow(svg, { x, y, values, kind, maxAbs, label: name, link, cell = CELL }) {
  const parent = linked(svg, link, { x, y, w: values.length * cell, h: cell });
  return G.vector(parent, { x, y, values: glyphValues(values), cell, orient: 'row', maxAbs, label: name, format: formatFor(kind) });
}

// A [4 × 4] grid of numbers. `mask` (true = visible) prints −∞; `hatch` (true = hatched) keeps the printed value.
export function numberGrid(svg, { x, y, values, kind, maxAbs, mask, hatch, label: name, rowLabels, colLabels, link, cell = CELL }) {
  const g = G.heatmap(svg, { x, y, values: values.map(glyphValues), mask, hatch, cell, maxAbs, label: name, rowLabels, colLabels, format: formatFor(kind) });
  if (link) g.dataset.link = link;
  return g;
}

// The four token chips; "sat" carries the selection mark wherever it appears.
export function tokenRow(svg, opacity = 1) {
  TOKENS.forEach((t, i) => fade(G.token(svg, { x: TOKEN_X[i], y: TOKEN_Y, text: t, index: i + 1 }), opacity));
  select(svg, TOKEN_X[QUERY], TOKEN_Y, G.tokenWidth(TOKENS[QUERY]), 24, opacity);
}

// Q, K and V of head A at 20 px; the first `rowsShown` rows are filled in (rows fill top to bottom).
// `hatchV` hatches the V rows whose weight for "sat" is 0 (masked out: they count for nothing, frame 7).
const V_HATCH = HEAD_A.mask[QUERY].map((visible) => [0, 1, 2, 3].map(() => !visible));
export function qkvGrids(svg, { rowsShown = 4, opacity = 1, hatchV = false } = {}) {
  const grids = ['q', 'k', 'v'].map((name) => {
    const values = QKV[name.toUpperCase()].map((row, i) => (i < rowsShown ? row : row.map(() => Number.NaN)));
    const g = G.matrix(svg, { x: MAT_X[name], y: MAT_Y, values, cell: GRID, maxAbs: SCALE.qkv, label: name.toUpperCase(), rowLabels: name === 'q' ? TOKENS : [], format: formatFor('score'), hatch: hatchV && name === 'v' ? V_HATCH : undefined });
    g.dataset.link = name;
    return fade(g, opacity);
  });
  label(svg, MAT_X.q, SHAPE_Y, '[4 tokens × d_head = 4]', { opacity });
  select(svg, MAT_X.q, MAT_Y + QUERY * GRID, 4 * GRID, GRID, opacity);
  return grids;
}

export function wBlock(svg, opacity = 1) {
  return fade(G.block(svg, { ...W_BLOCK, label: 'W_Q, W_K, W_V [8 × 4]' }), opacity);
}

// The causal mask as booleans (true = visible), revealed one anti-diagonal (i + j) at a time.
export function maskUpTo(diagonalsShown) {
  return TOKENS.map((_, i) => TOKENS.map((__, j) => j <= i || i + j > diagonalsShown));
}
